name: build addon

on:
  push:
    tags: ["*"]
    # To build on main/master branch, uncomment the following line:
    # branches: [ main , master ]

  pull_request:
    branches: [ main, master ]

  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout addon
      uses: actions/checkout@v4
      with:
        submodules: true
    
    - name: Checkout nvda-misc-deps
      uses: actions/checkout@v4
      with:
        repository: 'nvaccess/nvda-misc-deps'
        path: 'miscDeps'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        architecture: x86

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install pre-commit scons markdown

    - name: Code checks
      run: |
        $env:SKIP = "no-commit-to-branch"
        pre-commit run --all

    - name: Build addon
      run: |
        $env:PATH += ";$env:GITHUB_WORKSPACE\miscDeps\tools"
        scons

    - name: Build pot
      run: |
        $env:PATH += ";$env:GITHUB_WORKSPACE\miscDeps\tools"
        scons pot

    - uses: actions/upload-artifact@v4
      with:
        name: packaged_addon
        path: |
          ./*.nvda-addon
          ./*.pot

  upload_release:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: ["build"]
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: download releases files
      uses: actions/download-artifact@v4
    - name: Display structure of downloaded files
      run: ls -R
    - name: Calculate sha256
      run: |
        echo -e "\nSHA256: " >> changelog.md
        sha256sum packaged_addon/*.nvda-addon >> changelog.md

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          packaged_addon/*.nvda-addon
          packaged_addon/*.pot
        body_path: changelog.md
        fail_on_unmatched_files: true
        prerelease: ${{ contains(github.ref, '-') }}
